trigger:
  - AB#27-main

parameters:
  - name: environment
    type: string
    default: 'prod'
    values:
      - prod
      - qa
      - stage
      - local

variables:
  - name: dockerRegistryServiceConnection
    value: 'acr-ilifes-docker-connection-v2'
  - name: acrName
    value: 'ilifesregistry.azurecr.io'
  - name: imageNameFrontend
    value: 'marketplace-frontend'
  - name: imageNamebackend
    value: 'marketplace-backend'
  - name: sshServiceConnection
    value: 'ilifes-ssh-connection'
  - name: dockerImageTag
    value: 'latest'

stages:

# ------------------------------------------------
# Stage 1: Build Frontend Image & Push to ACR
# ------------------------------------------------
- stage: Build
  displayName: 'Build and Push Frontend Docker Image'
  jobs:
    - job: BuildFrontend
      displayName: 'Build Frontend Image'
      pool:
        name: 'Default'
      steps:

        - checkout: self

        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: login
            containerRegistry: $(dockerRegistryServiceConnection)

        - task: Docker@2
          displayName: 'Build Frontend Image'
          inputs:
            command: build
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageNameFrontend)
            dockerfile: frontend/Dockerfile
            buildContext: frontend
            tags: $(dockerImageTag)
            buildArguments: |
              BUILD_MODE=$(parameters.environment)
              CACHE_INVALIDATOR=$(Build.BuildId)

        - task: Docker@2
          displayName: 'Push Frontend Image'
          inputs:
            command: push
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageNameFrontend)
            tags: $(dockerImageTag)

# ------------------------------------------------
# Stage 2: Build Backend Image & Push to ACR
# ------------------------------------------------
- stage: BuildBackend
  displayName: "Build + Push Backend Image"
  jobs:
    - job: BuildBackendJob
      pool:
        name: 'Default'
      steps:
        - checkout: self

        - task: Docker@2
          displayName: "Build & Push Backend"
          inputs:
            command: buildAndPush
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageNamebackend)
            dockerfile: backend/Dockerfile
            buildContext: backend
            tags: latest

# ------------------------------------------------
# Stage 3: Deploy BOTH Frontend + Backend using docker-compose.yml
# ------------------------------------------------
- stage: DeployAll
  displayName: "Deploy using docker-compose.yml"
  dependsOn:
    - Build
    - BuildBackend

  jobs:
    - job: DeployAllJob
      pool:
        name: 'Default'

      steps:
        # Login to ACR BEFORE connecting via SSH
        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: login
            containerRegistry: $(dockerRegistryServiceConnection)

        - script: |
            echo "Waiting for ACR..."
            sleep 3
          displayName: "Wait for Image Availability"

        # Upload docker-compose-marketplace.yml using SCP
        - task: CopyFilesOverSSH@0
          displayName: "Upload docker-compose-marketplace.yml"
          inputs:
            sshEndpoint: $(sshServiceConnection)
            sourceFolder: "$(Build.SourcesDirectory)"
            contents: "docker-compose-marketplace.yml"
            targetFolder: "/var/www/html"

        # Deploy
        - task: SSH@0
          displayName: "Deploy using Compose on Remote Server"
          inputs:
            sshEndpoint: $(sshServiceConnection)
            runOptions: inline
            inline: |
              echo "Pulling latest images..."
              docker pull ilifesregistry.azurecr.io/buildprocure-frontend:latest
              docker pull ilifesregistry.azurecr.io/ilifes-items-backend:latest

              echo "Navigating to deployment directory..."
              cd /var/www/html

              echo "Stopping existing containers..."
              docker-compose -f docker-compose-marketplace.yml down 2>&1 || true

              echo "Starting updated containers..."
              docker-compose -f docker-compose-marketplace.yml up -d --force-recreate 2>&1

              echo "✓ Deployment completed!"
              docker ps -a