trigger:
  - AB#27-main

parameters:
  - name: environment
    type: string
    default: 'prod'
    values:
      - prod
      - qa
      - stage
      - local

variables:
  - name: dockerRegistryServiceConnection
    value: 'ilifes-acr-docker'
  - name: acrName
    value: 'ilifesregistry.azurecr.io'
  - name: imageNameFrontend
    value: 'marketplace-frontend'
  - name: imageNamebackend
    value: 'marketplace-backend'
  - name: sshServiceConnection
    value: 'ilifes-ssh-connection'
  - name: dockerImageTag
    value: 'latest'

stages:

# ------------------------------------------------
# Stage 1: Build Frontend Image & Push to ACR
# ------------------------------------------------
- stage: Build
  displayName: 'Build and Push Frontend Docker Image'
  jobs:
    - job: BuildFrontend
      displayName: 'Build Frontend Image'
      pool:
        name: 'Default'
      steps:

        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Install Node.js'

        - script: |
            if [ "${{ parameters.environment }}" = "prod" ]; then
              echo "##vso[task.setvariable variable=VITE_API_URL]http://buildprocure.com:8085"
            elif [ "${{ parameters.environment }}" = "qa" ]; then
              echo "##vso[task.setvariable variable=VITE_API_URL]https://qa.buildprocure.com:8085"
            elif [ "${{ parameters.environment }}" = "stage" ]; then
              echo "##vso[task.setvariable variable=VITE_API_URL]https://stage.buildprocure.com:8085"
            else
              echo "##vso[task.setvariable variable=VITE_API_URL]http://localhost:8081"
            fi
          displayName: 'Set VITE_API_URL'

        - script: |
            cd frontend
            export VITE_API_URL=$(VITE_API_URL)
            npm ci
            npm run build:${{ parameters.environment }}
          displayName: 'Build React Frontend'

        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: login
            containerRegistry: $(dockerRegistryServiceConnection)

        - task: Docker@2
          displayName: 'Build Frontend Image'
          inputs:
            command: build
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageNameFrontend)
            dockerfile: frontend/Dockerfile
            buildContext: frontend
            tags: $(dockerImageTag)

        - task: Docker@2
          displayName: 'Push Frontend Image'
          inputs:
            command: push
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageNameFrontend)
            tags: $(dockerImageTag)

# ------------------------------------------------
# Stage 2: Build Backend Image & Push to ACR
# ------------------------------------------------
- stage: BuildBackend
  displayName: "Build + Push Backend Image"
  jobs:
    - job: BuildBackendJob
      pool:
        name: 'Default'
      steps:
        - checkout: self

        - task: Docker@2
          displayName: "Build & Push Backend"
          inputs:
            command: buildAndPush
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageNamebackend)
            dockerfile: backend/Dockerfile
            buildContext: backend
            tags: latest

# ------------------------------------------------
# Stage 3: Deploy BOTH Frontend + Backend using docker-compose.yml
# ------------------------------------------------
- stage: DeployAll
  displayName: "Deploy using docker-compose.yml"
  dependsOn:
    - Build
    - BuildBackend

  jobs:
    - job: DeployAllJob
      pool:
        name: 'Default'

      steps:
        # Login to ACR BEFORE connecting via SSH
        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: login
            containerRegistry: $(dockerRegistryServiceConnection)

        - script: |
            echo "Waiting for ACR..."
            sleep 3
          displayName: "Wait for Image Availability"

        # Upload docker-compose-marketplace.yml using SCP
        - task: SSH@0
          displayName: "Upload docker-compose-marketplace.yml to Server"
          inputs:
            sshEndpoint: $(sshServiceConnection)
            runOptions: inline
            inline: |
              echo "Uploading compose file..."
              scp -o StrictHostKeyChecking=no \
                "$(Build.SourcesDirectory)/docker-compose-marketplace.yml" \
                $(username)@$(hostname):/var/www/marketplace-deploy/

        # Deploy
        - task: SSH@0
          displayName: "Deploy using Compose on Remote Server"
          inputs:
            sshEndpoint: $(sshServiceConnection)
            runOptions: inline
            inline: |
              echo "Pulling latest images..."
              docker pull ilifesregistry.azurecr.io/buildprocure-frontend:latest
              docker pull ilifesregistry.azurecr.io/ilifes-items-backend:latest

              echo "Navigating to deployment directory..."
              cd /var/www/marketplace-deploy

              echo "Stopping existing containers..."
              docker-compose -f docker-compose-marketplace.yml down --remove-orphans || true

              echo "Starting updated containers..."
              docker-compose -f docker-compose-marketplace.yml up -d --force-recreate

              echo "✓ Deployment completed!"
              docker ps -a