trigger:
  - AB#27-main

parameters:
  - name: environment
    type: string
    default: 'prod'
    values:
      - prod
      - qa
      - stage
      - local

variables:
  - name: dockerRegistryServiceConnection
    value: 'ilifes-acr-docker'
  - name: acrName
    value: 'ilifesregistry.azurecr.io'
  - name: imageName
    value: 'buildprocure-frontend'
  - name: sshServiceConnection
    value: 'ilifes-ssh-connection'
  - name: dockerImageTag
    value: 'latest'

stages:

# ------------------------------
# Stage 1: Build Docker Image
# ------------------------------
- stage: Build
  displayName: 'Build and Push Frontend Docker Image'
  jobs:
    - job: BuildFrontend
      displayName: 'Build Frontend Image'
      pool:
        name: 'Default'
      steps:

        # Checkout frontend repo
        - checkout: self

        # Install Node
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Install Node.js'

        # Set VITE_API_URL dynamically based on environment
        - script: |
            if [ "${{ parameters.environment }}" = "prod" ]; then
              echo "##vso[task.setvariable variable=VITE_API_URL]http://buildprocure.com:8085"
            elif [ "${{ parameters.environment }}" = "qa" ]; then
              echo "##vso[task.setvariable variable=VITE_API_URL]https://qa.buildprocure.com:8085"
            elif [ "${{ parameters.environment }}" = "stage" ]; then
              echo "##vso[task.setvariable variable=VITE_API_URL]https://stage.buildprocure.com:8085"
            else
              echo "##vso[task.setvariable variable=VITE_API_URL]http://localhost:8081"
            fi
          displayName: 'Set VITE_API_URL for environment'

        # Install dependencies & build in frontend folder
        - script: |
            cd $(Build.SourcesDirectory)/frontend
            export VITE_API_URL=$(VITE_API_URL)
            npm ci
            npm run build:${{ parameters.environment }}
          displayName: 'Build React Frontend'


        # Debug built dist folder
        - script: |
            cd $(Build.SourcesDirectory)/frontend/dist
            ls -la
            #display VITE_API_URL value
            echo "VITE_API_URL: $(VITE_API_URL)"
          displayName: 'Show dist folder and VITE_API_URL'

        # Login to ACR
        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: login
            containerRegistry: $(dockerRegistryServiceConnection)

        # Build & push Docker image
        - task: Docker@2
          displayName: 'Build and Push Frontend Image'
          inputs:
            command: buildAndPush
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageName)
            dockerfile: $(Build.SourcesDirectory)/frontend/Dockerfile
            buildContext: $(Build.SourcesDirectory)/frontend
            tags: $(dockerImageTag)
            arguments: >
              --build-arg VITE_API_URL=$(VITE_API_URL)
              --build-arg BUILD_MODE=${{ parameters.environment }}
# ------------------------------
# Stage 2: Deploy to Server
# ------------------------------
- stage: Deploy
  dependsOn: Build
  jobs:
    - job: DeployContainer
      pool:
        name: 'Default'
      steps:
        - task: SSH@0
          displayName: Deploy to Server
          inputs:
            sshEndpoint: $(sshServiceConnection)
            runOptions: inline
            inline: |
              echo "Pulling latest image..."
              docker pull $(acrName)/$(imageName):$(dockerImageTag)

              echo "Restarting container..."
              docker stop ilifes-items-frontend || true
              docker rm ilifes-items-frontend || true

              docker run -d --name ilifes-items-frontend -p 3000:80 \
                $(acrName)/$(imageName):$(dockerImageTag)

              echo "🚀 Frontend deployed successfully!"
              docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"

- stage: BuildBackend
  displayName: "Build + Push Backend Image"
  jobs:
    - job: BuildBackendJob
      pool:
        name: 'Default'
      steps:
        - checkout: self

        - task: Docker@2
          inputs:
            command: buildAndPush
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: ilifes-items-backend
            dockerfile: backend/Dockerfile
            buildContext: backend
            tags: latest

- stage: DeployBackend
  displayName: "Deploy Backend Container"
  dependsOn: BuildBackend
  jobs:
    - job: DeployBackendJob
      pool:
        name: 'Default'
      steps:
        - task: SSH@0
          inputs:
            sshEndpoint: $(sshServiceConnection)
            runOptions: "inline"
            inline: |
              docker pull $(acrName)/ilifes-items-backend:latest
              docker stop ilifes-items-backend 2>/dev/null || true
              docker rm ilifes-items-backend 2>/dev/null || true

              docker run -d --name ilifes-items-backend \
                -p 8085:80 \
                $(acrName)/ilifes-items-backend:latest

              docker ps -a
              echo "✓ Backend deployed!"
