FROM php:8.2-apache

# Enable Apache modules
RUN a2enmod rewrite headers proxy proxy_fcgi

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql

# Copy custom Apache config
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Copy backend (Slim)
COPY ../backend /var/www/html/api

# Copy frontend build
COPY ../frontend/dist /var/www/html

# Fix permissions
RUN chown -R www-data:www-data /var/www/html
